export const CHANGE_PAGE_NR = 'CHANGE_PAGE_NR';
export const RESET_PAGINATION = 'RESET_PAGINATION';
export const UPDATE_PAGINATION_INFO = 'UPDATE_PAGINATION_INFO';

export const CHANGE_PAGE_NR_MODAL = 'CHANGE_PAGE_NR_MODAL';
export const RESET_PAGINATION_MODAL = 'RESET_PAGINATION_MODAL';
export const UPDATE_PAGINATION_INFO_MODAL = 'UPDATE_PAGINATION_INFO_MODAL';

