export const RESET_ITL = 'RESET_ITL';

export const CHANGE_PERSONALIZE_TAGS_PANEL_PROPERTIES = 'CHANGE_PERSONALIZE_TAGS_PANEL_PROPERTIES';

export const GET_ITL_MACROS_START = 'GET_ITL_MACROS_START';
export const GET_ITL_MACROS_SUCCESS = 'GET_ITL_MACROS_SUCCESS';
export const GET_ITL_MACROS_FAIL = 'GET_ITL_MACROS_FAIL';

export const SET_CKEDITOR_MODE = 'SET_CKEDITOR_MODE';
