export const ENTITY_FETCH_START = 'ENTITY_FETCH_START';
export const ENTITY_FETCH_SUCCESS = 'ENTITY_FETCH_SUCCESS';
export const ENTITY_FETCH_FAILED = 'ENTITY_FETCH_FAILED';

export const ENTITY_OPERATIONS_MERGE = 'ENTITY_OPERATIONS_MERGE';
export const ENTITY_OPERATIONS_START = 'ENTITY_OPERATIONS_START';
export const ENTITY_OPERATIONS_SUCCESS = 'ENTITY_OPERATIONS_SUCCESS';
export const ENTITY_OPERATIONS_FAILED = 'ENTITY_OPERATIONS_FAILED';

export const PROCESS_OPERATION = 'PROCESS_OPERATION';
export const RESET_OPERATION = 'RESET_OPERATION';
