export const SETUP_ENTITY = 'SETUP_ENTITY';

export const SELECT_TREE_ITEM = 'SELECT_TREE_ITEM';
export const EXPAND_TREE_ITEM = 'EXPAND_TREE_ITEM';
export const EXPAND_ALL_TREE_ITEMS = 'EXPAND_ALL_TREE_ITEMS';

export const SELECT_ENTITY = 'SELECT_ENTITY';
export const SELECT_ALL_ENTITIES = 'SELECT_ALL_ENTITIES';

export const TOGGLE_CREATE_FOLDER = 'TOGGLE_CREATE_FOLDER';
export const TOGGLE_FILTERS = 'TOGGLE_FILTERS';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const TOGGLE_ACTIVE_FILTERS = 'TOGGLE_ACTIVE_FILTERS';

export const SELECT_TREE_ITEM_IN_MODAL = 'SELECT_TREE_ITEM_IN_MODAL';
export const TOGGLE_MOVE_MODAL_STATE = 'TOGGLE_MOVE_MODAL_STATE';
export const EXPAND_MODAL_TREE_ITEM = 'EXPAND_MODAL_TREE_ITEM';
export const COLLECT_ENTITY_FOR_ACTIONS = 'COLLECT_ENTITY_FOR_ACTIONS';

export const TOGGLE_DELETE_MODAL_STATE = 'TOGGLE_DELETE_MODAL_STATE';

export const SELECT_REPORTS_TAB = 'SELECT_REPORTS_TAB';
export const HANDLE_SORTING = 'HANDLE_SORTING';

export const CREATE_NEW_FOLDER_START = 'CREATE_NEW_FOLDER_START';
export const CREATE_NEW_FOLDER_SUCCESS = 'CREATE_NEW_FOLDER_SUCCESS';
export const CREATE_NEW_FOLDER_FAIL = 'CREATE_NEW_FOLDER_FAIL';

export const RENAME_ENTITY_START = 'RENAME_ENTITY_START';
export const RENAME_ENTITY_SUCCESS = 'RENAME_ENTITY_SUCCESS';
export const RENAME_ENTITY_FAIL = 'RENAME_ENTITY_FAIL';

export const FOCUS_ON_CREATION_WIDGET = 'FOCUS_ON_CREATION_WIDGET';
export const RESET_FOCUS_ON_CREATION_WIDGET = 'RESET_FOCUS_ON_CREATION_WIDGET';

export const SET_IS_RENAMING_ENTITY = 'SET_IS_RENAMING_ENTITY';

export const CREATE_DELETE_CONTENT = 'CREATE_DELETE_CONTENT';
export const COLLECT_BREADCRUMB_PATH = 'COLLECT_BREADCRUMB_PATH';
export const SELECT_CONTENT_ITEM_WIDGETS = 'SELECT_CONTENT_ITEM_WIDGETS';
export const RESET_WIDGETS = 'RESET_WIDGETS';
