export default {
  IMG_DIR: `/static/${process.env.VERSION}/img/`,
  API_ENDPOINTS: {
    baseUrl: '/api/v1/',

    capabilities: 'accounts/capabilities',

    genericFolderRename: ':entityGroup/folders/rename',
    genericEntityRename: ':entityGroup/rename',
    genericFoldersTree: ':entityGroup/folders/tree',
    genericFolderContents: ':entityGroup/folders/:folderId/children',
    genericCreateFolder: ':entityGroup/folders',
    genericMoveEntities: ':entityGroup/move/bulk',
    genericDeleteEntities: ':entityGroup/delete/bulk',
    genericDuplicateEntity: ':entityGroup/duplicate',
    genericFilterEntities: ':entityGroup/filter',
    genericSearchEntities: ':entityGroup/search',
    genericNameValidationForEntities: ':entityGroup/name/validate',

    // REPORTS: email-tickets
    getReportsInlineClicks: 'ticketreports/inline_click',
    getReportsMailSummary: 'ticketreports/mailing_summary',
    getReportsLinks: 'ticketreports/link',
    getReportsDetails: 'ticketreports/mailing-details',
    getReportsLinksUpdate: 'ticketreports/link-update',
    getReportsISPDelivery: 'ticketreports/domain_statistic',
    downloadReportsMailResults: 'ticketreports/mailing_results',
    getReportsFolderContents: 'ticketreports/folders/:id/children',

    // REPORTS: campaigns
    getCampaignsSummary: 'campaigntags/report_campaign',
    downloadCampaignReport: 'campaigntags/download_report',
    createCampaign: 'campaigntags',

    // SUBSCRIBER OVERVIEW
    downloadSubscriberMetrics: 'ticketreports/metrics',
    downloadGrouthChurn: 'ticketreports/churn',
    downloadOptOuts: 'ticketreports/download_optouts',
    downloadBounces: 'ticketreports/download_bounces',

    // FILTERS
    getTablesAndAttributes: 'customdatatables/tables/all/columns',
    getTablesAndAttributesIMM: 'aqlfilters/tables/all/columns',
    getCDTFilters: 'aqlfilters/cdt/all',
    getIMMFilters: 'aqlfilters/imm/all',

    // Custom Data Tables API
    tablesTree: 'customdatatables/folders/tree',

    getTableFolderContents: 'customdatatables/folders/:folderId/children',
    getModalTableFolderContents: 'customdatatables/folders/:id/children',
    getSendableTableFolderContents: 'customdatatables/folders/:id/children?sendable=1',
    getSendableTestableTableFolderContents: 'customdatatables/folders/:id/children?sendable=1&testable=1',
    getTestableTableFolderContents: 'customdatatables/folders/:id/children?testable=1',
    createNewFolderTable: 'customdatatables/folders/create',
    // filterTableContents: 'customdatatables/filter',
    deleteTableFolder: 'customdatatables/folders/delete/:folderId',
    deleteTable: 'customdatatables/tables/delete/:tableId',
    saveDataTable: 'customdatatables/tables/create_table',
    getTableDataTypes: 'customdatatables/tables/get_data_types',
    getTableMeta: 'customdatatables/tables/:tableId/meta',
    updateDataTable: 'customdatatables/tables/:tableId',
    uploadRecords: 'customdatatables/records/upload',
    uploadFTPRecords: 'customdatatables/records/ftp/upload',
    getTableData: 'customdatatables/tables/:tableId/table_data',
    removeRecord: 'customdatatables/records/delete',
    completeUpload: 'customdatatables/records/insert',
    completeFTPUpload: 'customdatatables/records/ftp/insert',
    exportTable: 'customdatatables/tables/:tableId/export',
    cleanTable: 'customdatatables/table/:tableId/records',
    moveItem: 'customdatatables/:itemType/:itemId/to/:folderId',
    updateRecord: 'customdatatables/records/edit',
    deleteTablesAndFolders: 'customdatatables/folders/deletebulk',
    renameDataTableFolder: 'customdatatables/folders/rename',
    moveFoldersAndTables: 'customdatatables/folders/movebulk',
    duplicateTable: 'customdatatables/tables/duplicate_table/:tableId',
    getFTP: 'customdatatables/records/ftp',
    updateDynamicTable: 'customdatatables/dynamic/:tableId',
    // createDynamicTable: 'customdatatables/dynamic/changethis',
    getSchemas: 'customdatatables/client/:clientId/schema/:schema/tables',
    getTableColumns: 'customdatatables/client/:clientId/tables/:tableId/columns',
    handleShowPreview: 'customdatatables/tables/create_dynamic_table',
    getTableRelationship: 'customdatatables/relationships/table/:clientId/:schema/:tableId',
    getRelationsshipsBetween: 'customdatatables/relationships/between',
    refreshDynamicTable: 'customdatatables/dynamic/:tableId/refresh',

    dynamicMembersSet: 'emaillists/:listId/dynamic_membership_set',
    dynamicMembersGet: 'emaillists/:listId/dynamic_membership_get',
    dynamicMembersRefresh: 'emaillists/:listId/dynamic_membership_refresh',

    getListStats: 'emaillists/:listId/stats',

    // query preview route
    showSQLFilter: 'aqlfilters/preview_filter',

    foldersTree: 'emails/folders/tree',
    createNewFolder: 'emails/folders',
    getFolderContents: 'emails/folders/:folderId/children',
    getEmailFolderContents: 'emails/folders/:id/children',
    filterContents: 'emails/filter',
    moveFolder: 'emails/folders/move/bulk',

    // Auth API
    status: 'status',
    login: 'login',
    logout: 'logout',
    sessionCheck: 'accounts/check',
    userInfo: 'accounts/check',
    userInfoById: 'accounts/:id/check',
    updateUserInfo: 'accounts/{0}',
    resetPassword: 'accounts/reset-password',
    validateToken: 'accounts/token/',
    updatePassword: 'accounts/update-password',
    changeProfilePassword: 'accounts/{0}/change-password',
    profileMenuTabs: 'accounts/{0}/menu-tabs',
    profileDefaultPreviewEmail: 'accounts/{0}/default-preview-email',

    textFileUpload: 'emails/text/upload',
    htmlFileUpload: 'emails/html/upload',
    deleteFoldersAndEmails: 'emails/folders/delete/bulk',
    searchFoldersAndEmails: 'emails/search',

    // Content creation routes
    emails: 'emails/text',
    getEmailProperties: 'emails/:id',
    updateTextEmailProperties: 'emails/text',
    updateTextEmailContent: 'emails/text/content',
    getEmail: 'emails/:emailId',
    addContent: 'emails/text',
    getBeeFreeContent: 'emails/bee-free-template/:id',
    spellCheck: 'emails/text/spellcheck',
    previewTextEmail: 'emails/text/preview',
    previewHtmlEmail: 'emails/html/preview',
    emailListsFolders: 'emaillists/folders/tree',
    emailListsChildren: 'emaillists/folders/:id/children',
    sendTestEmails: 'emails/send_test_email',
    testHistory: 'emails/:id/test-history',
    emailLists: 'emaillists',
    emailListsUpdate: 'emaillists/update/:id',
    emailListsSubscribers: 'emaillists/:id/contacts',
    emailListsManuallyAddRemove: 'emaillists/:id',
    listsContactsSummary:'emaillists/count_lists_contacts',
    cleanLists: 'emaillists/:id/clean',
    cleanSuppressionLists: 'emaillists/:id/delete_suppresion_records',
    subscribersUploadFinish: 'emaillists/uploadfinish/:id',
    searchContact: 'contacts/search',
    specialQueryList: 'emaillists/get_query',
    runSpecialQuery: 'emaillists/:id/special_query',
    listSummary: 'emaillists/:id/summary',
    mergeLists: 'emaillists/:id/merge',
    deduplicate: 'emaillists/:id/deduplicate',
    suppressionListUpload: 'emaillists/:id/suppression_upload',
    splitList: 'emaillists/:id/split',
    listHistory: 'emaillists/:id/history',
    filterAttributes: 'emaillists/attributes',
    exportList: 'emaillists/download/:id',

    createDynamicList: 'emaillists/create_dynamic',
    getListsFolderContent: 'emaillists/filter',
    getSuppressionListsFolderContent: 'emaillists/folders/:id/children?type=Suppression',
    getNonSuppressionListsFolderContent: 'emaillists/folders/:id/children?type=Dynamic&type=Static&type=Test',
    getListMembership: 'emaillists/contact_email_lists/:contactId',

    headersAndFootersFolderContents: 'emailsections/folders/:folderId/children',
    headersAndFootersFolderTree: 'emailsections/folders/tree',
    createHeaderFooterFolder: 'emailsections/folders',
    renameHeaderFooterFolder: 'emailsections/folders/rename',
    moveHeaderFooterFolder: 'emailsections/folders/move/bulk',
    deleteHeaderFooter: 'emailsections/folders/delete/bulk',
    duplicateHeaderFooter: 'emailsections/:id/duplicate',
    getHeaderFooter: 'emailsections/:id',
    saveHeaderFooterProperites: 'emailsections/',
    saveHeaderFooterContent: 'emailsections/content',
    filterHeadersFooters: 'emailsections/filter',
    uploadHeadersFooters: 'emailsections/upload',

    htmlEmailProperties: 'emails/html',
    addHtmlContent: 'emails/html/content',
    autogenerateText: 'emails/html/autogenerate',
    htmlSpellcheck: 'emails/html/spellcheck',
    spamCheck: 'emails/spam-check',
    duplicateEmail: 'emails/duplicate',

    createHtmlTemplateProperties: 'contenttemplates',
    addHtmlTemplateContent: 'contenttemplates/html',
    getTemplateFolderContents: 'contenttemplates/folders/:folderId/children',
    getTemplateProperties: 'contenttemplates/:id',
    templateFolderTree: 'contenttemplates/folders/tree',
    renameTemplateFolder: 'contenttemplates/folders/rename',
    moveTemplateFolder: 'contenttemplates/folders/move/bulk',
    deleteFoldersAndTemplates: 'contenttemplates/folders/delete/bulk',
    createNewTemplateFolder: 'contenttemplates/folders',
    searchInTemplatesAndFolders: 'contenttemplates/search/',
    filterTemplatesAndFolders: 'contenttemplates/filter',
    getTemplateEmailsBasedOnTemplate: 'emails/search',
    searchEmailTemplates: 'contenttemplates/search/emails',
    fullTemplateTree: 'contenttemplates/folders/full-tree',
    publishTemplate: 'contenttemplates/activate',
    unpublishTemplate: 'contenttemplates/deactivate',
    htmlTemplateUpload: 'contenttemplates/upload',

    sampleTemplates: 'contenttemplates/samples',

    //assets endpoints
    assetsValidation: 'assets/validate',
    assetsUpload: 'assets/upload',
    getAsset: 'assets/summary/:id',
    saveAsset: 'assets/update',

    //system notices endpoints
    getAllSystemNotices: 'systemnotices/all',
    getLatestSystemNotices: 'systemnotices/latest',
    getNewSystemNotices: 'systemnotices/new',
    acknowledgeSystemNotices: 'systemnotices/acknowledge',

    getAllContactsList: 'contacts/list',
    getAllContactsProps: 'contacts/columns',
    contactsProps: 'contacts/columns',
    contactsUpload: 'emaillists/upload',
    deleteContacts: 'contacts',
    addContacts: 'contacts',
    contactDetails: 'contacts/history/:id',
    editContact: 'contacts/:id',
    getTopicsForContact: 'contacts/topics/:id',
    finishContactUpload: 'contacts/upload',
    uploadOptedOutContacts: 'contacts/optouts',

    // export types endpoints
    bouncedExport: 'contacts/bounces_download',
    optoutsExport: 'contacts/optouts_download',
    listsExport: 'emaillists/download/:id',

    filterFolderTree: 'aqlfilters/folders/tree',
    filterFolderContents: 'aqlfilters/folders/:folderId/children',
    createNewFilterFolder: 'aqlfilters/folders',
    renameFilterFolder: 'aqlfilters/folders/rename',
    searchInFilters: 'aqlfilters/search',
    moveFoldersAndFilters: 'aqlfilters/folders/move/bulk',
    deleteFoldersAndFilters: 'aqlfilters/folders/delete/bulk',
    duplicateFilter: 'aqlfilters/duplicate',
    createNewFilter: 'aqlfilters/:filterType',
    updateFilter: 'aqlfilters',
    getFilterProperties: 'aqlfilters/:id',
    saveQueryData: 'aqlfilters/content',

    getTopics: 'contacts/topics',
    getAllTopics: 'topics/',
    createTopic: 'contacts/topics/create',
    renameTopic: 'contacts/topics/rename',
    deleteTopics: 'contacts/topics/delete',

    //settings
    webAnalytics: 'settings/webanalytics',
    getSubclientsList: 'accounts/subclients',
    getDTSubclientsList: 'accounts/dt_subclients',
    getSettingsSubclientsList: 'settings/subclients/search',
    switchSubclient: 'accounts/:id/switch',
    addSubclientValidation: 'settings/subclients/validate',
    submitNewSubclient: 'settings/subclients',
    getSubclientDetails: 'settings/:id/subclients',
    subclientPrimaryContact: 'settings/:id/primary_contact',
    clientSettings: 'settings/client',
    getUsers: 'settings/user',
    editUser: 'settings/user/:id',
    editUserPassword: 'accounts/:id/change-account-password',
    enableUser: 'accounts/:id/enable',
    getUserHistory: 'settings/:id/user_history',
    getUserCategories: 'settings/category',
    saveUserCategories: 'settings/category',
    deliveryManagement: 'settings/delivery-management',
    addUser: 'accounts',
    managePermissions: 'settings/user/:userId/capabilities',

    getSettingsDatabaseItlTable: 'settings/database/macros',
    deleteItlMacro: 'settings/database/delete',
    saveItlMacros: 'settings/database',
    updateDatabasePage: 'settings/database/edit',

    getAutomationItem: 'automation/:id',
    saveAutomationProperties: 'automation',
    automationRunOnce: 'automation/run-once',
    automationStop: 'automation/stop',
    saveItemStatus: 'automation/save-item-status',
    saveAutomationConfiguration: 'automation/send-configuration',
    saveSendTemplatesConfiguration: 'automationsendtemplates',
    getAutomationConfiguration: 'automation/send-configuration/:id',
    getUserIPAddresses: 'automation/ip-addresses',
    getUserCampaignList: 'automation/campaigns',
    getAutomationSchedule: 'automation/:id/schedule',
    getAutomationRunLog: 'automation/:id/run-log',
    getAutomationrunLogEmails: 'automation/:id/notification-recipients',
    automationSendTemplates: 'automationsendtemplates',
    getSendTemplatesItem: 'automationsendtemplates/:id',
    getSendTemplatesFolderContents: 'automationsendtemplates/folders/:id/children',
    checkName: 'automation/check_name',
    imageUpload: 'image',
  },
  DRAG_AND_DROP_TYPES: {
    FOLDER: 'folder',
    TICKET: 'ticket'
  },
  DATE_FORMATS: {
    date: 'MM-DD-YYYY',
    dateAndTime: 'MM-DD-YYYY hh:mm A'
  },
  EMPTY_CHAR: '\u200C',

  operatorsDefinitions: {
    ComparisonOperator: {
      'eq': 'equal',
      'ne': 'not equal',
      'lt': 'less than',
      'le': 'less than or equal',
      'gt': 'greater than',
      'ge': 'greater than or equal',
      'bw': 'begins with',
      'bn': 'doesn\'t begin with',
      'in': 'is in / LIKE',
      'ni': 'is not in / NOT LIKE',
      'ew': 'ends with',
      'en': 'does\'t end with',
      'cn': 'contains',
      'nc': 'doesn\'t contain'
    },

    DateOperator: {
      'rg': 'range',
      'so': 'some other operator'
    },

    LogicalOperator: {
      1: 'AND',
      0: 'OR'
    }
  },
  chartColors: [
    {
      key: 'active',
      displayName: 'Active',
      color:"#47c075",
      highlight: "#47c075",
    },
    {
      key: 'bounces',
      displayName: 'Bounces',
      color: "#f2a640",
      highlight: "#f2a640",
    },
    {
      key: 'unsubscribe',
      displayName: 'Unsubscribe',
      color: "#f24040",
      highlight: "#f24040",
    },
    {
      key: 'complaints',
      displayName: 'Complaints',
      color: "#707070",
      highlight: "#707070",
    }
  ],
  timeZone: [
      {label: '(UTC-11:00) Midway Island', value: 'Pacific/Midway'},
      {label: '(UTC-11:00) Samoa', value: 'Pacific/Samoa'},
      {label: '(UTC-10:00) Hawaii', value: 'Pacific/Honolulu'},
      {label: '(UTC-09:00) Alaska', value: 'US/Alaska'},
      {label: '(UTC-08:00) Pacific Time (US &amp; Canada)', value: 'America/Los_Angeles'},
      {label: '(UTC-08:00) Tijuana', value: 'America/Tijuana'},
      {label: '(UTC-07:00) Arizona', value: 'US/Arizona'},
      {label: '(UTC-07:00) Chihuahua', value: 'America/Chihuahua'},
      {label: '(UTC-07:00) La Paz', value: 'America/Chihuahua'},
      {label: '(UTC-07:00) Mazatlan', value: 'America/Mazatlan'},
      {label: '(UTC-07:00) Mountain Time (US &amp; Canada)', value: 'US/Mountain'},
      {label: '(UTC-06:00) Central America', value: 'America/Managua'},
      {label: '(UTC-06:00) Central Time (US &amp; Canada)', value: 'US/Central'},
      {label: '(UTC-06:00) Guadalajara', value: 'America/Mexico_City'},
      {label: '(UTC-06:00) Mexico City', value: 'America/Mexico_City'},
      {label: '(UTC-06:00) Monterrey', value: 'America/Monterrey'},
      {label: '(UTC-06:00) Saskatchewan', value: 'Canada/Saskatchewan'},
      {label: '(UTC-05:00) Bogota', value: 'America/Bogota'},
      {label: '(UTC-05:00) Eastern Time (US &amp; Canada)', value: 'US/Eastern'},
      {label: '(UTC-05:00) Indiana (East)', value: 'US/East-Indiana'},
      {label: '(UTC-05:00) Lima', value: 'America/Lima'},
      {label: '(UTC-05:00) Quito', value: 'America/Bogota'},
      {label: '(UTC-04:00) Atlantic Time (Canada)', value: 'Canada/Atlantic'},
      {label: '(UTC-04:30) Caracas', value: 'America/Caracas'},
      {label: '(UTC-04:00) La Paz', value: 'America/La_Paz'},
      {label: '(UTC-04:00) Santiago', value: 'America/Santiago'},
      {label: '(UTC-03:30) Newfoundland', value: 'Canada/Newfoundland'},
      {label: '(UTC-03:00) Brasilia', value: 'America/Sao_Paulo'},
      {label: '(UTC-03:00) Buenos Aires', value: 'America/Argentina/Buenos_Aires'},
      {label: '(UTC-03:00) Georgetown', value: 'America/Argentina/Buenos_Aires'},
      {label: '(UTC-03:00) Greenland', value: 'America/Godthab'},
      {label: '(UTC-02:00) Mid-Atlantic', value: 'America/Noronha'},
      {label: '(UTC-01:00) Azores', value: 'Atlantic/Azores'},
      {label: '(UTC-01:00) Cape Verde Is.', value: 'Atlantic/Cape_Verde'},
      {label: '(UTC+00:00) Casablanca', value: 'Africa/Casablanca'},
      {label: '(UTC+00:00) Edinburgh', value: 'Europe/London'},
      {label: '(UTC+00:00) Greenwich Mean Time : Dublin', value: 'Etc/Greenwich'},
      {label: '(UTC+00:00) Lisbon', value: 'Europe/Lisbon'},
      {label: '(UTC+00:00) London', value: 'Europe/London'},
      {label: '(UTC+00:00) Monrovia', value: 'Africa/Monrovia'},
      {label: '(UTC+00:00) UTC', value: 'UTC'},
      {label: '(UTC+01:00) Amsterdam', value: 'Europe/Amsterdam'},
      {label: '(UTC+01:00) Belgrade', value: 'Europe/Belgrade'},
      {label: '(UTC+01:00) Berlin', value: 'Europe/Berlin'},
      {label: '(UTC+01:00) Bern', value: 'Europe/Berlin'},
      {label: '(UTC+01:00) Bratislava', value: 'Europe/Bratislava'},
      {label: '(UTC+01:00) Brussels', value: 'Europe/Brussels'},
      {label: '(UTC+01:00) Budapest', value: 'Europe/Budapest'},
      {label: '(UTC+01:00) Copenhagen', value: 'Europe/Copenhagen'},
      {label: '(UTC+01:00) Ljubljana', value: 'Europe/Ljubljana'},
      {label: '(UTC+01:00) Madrid', value: 'Europe/Madrid'},
      {label: '(UTC+01:00) Paris', value: 'Europe/Paris'},
      {label: '(UTC+01:00) Prague', value: 'Europe/Prague'},
      {label: '(UTC+01:00) Rome', value: 'Europe/Rome'},
      {label: '(UTC+01:00) Sarajevo', value: 'Europe/Sarajevo'},
      {label: '(UTC+01:00) Skopje', value: 'Europe/Skopje'},
      {label: '(UTC+01:00) Stockholm', value: 'Europe/Stockholm'},
      {label: '(UTC+01:00) Vienna', value: 'Europe/Vienna'},
      {label: '(UTC+01:00) Warsaw', value: 'Europe/Warsaw'},
      {label: '(UTC+01:00) West Central Africa', value: 'Africa/Lagos'},
      {label: '(UTC+01:00) Zagreb', value: 'Europe/Zagreb'},
      {label: '(UTC+02:00) Athens', value: 'Europe/Athens'},
      {label: '(UTC+02:00) Bucharest', value: 'Europe/Bucharest'},
      {label: '(UTC+02:00) Cairo', value: 'Africa/Cairo'},
      {label: '(UTC+02:00) Harare', value: 'Africa/Harare'},
      {label: '(UTC+02:00) Helsinki', value: 'Europe/Helsinki'},
      {label: '(UTC+02:00) Istanbul', value: 'Europe/Istanbul'},
      {label: '(UTC+02:00) Jerusalem', value: 'Asia/Jerusalem'},
      {label: '(UTC+02:00) Kyiv', value: 'Europe/Helsinki'},
      {label: '(UTC+02:00) Pretoria', value: 'Africa/Johannesburg'},
      {label: '(UTC+02:00) Riga', value: 'Europe/Riga'},
      {label: '(UTC+02:00) Sofia', value: 'Europe/Sofia'},
      {label: '(UTC+02:00) Tallinn', value: 'Europe/Tallinn'},
      {label: '(UTC+02:00) Vilnius', value: 'Europe/Vilnius'},
      {label: '(UTC+03:00) Baghdad', value: 'Asia/Baghdad'},
      {label: '(UTC+03:00) Kuwait', value: 'Asia/Kuwait'},
      {label: '(UTC+03:00) Minsk', value: 'Europe/Minsk'},
      {label: '(UTC+03:00) Nairobi', value: 'Africa/Nairobi'},
      {label: '(UTC+03:00) Riyadh', value: 'Asia/Riyadh'},
      {label: '(UTC+03:00) Volgograd', value: 'Europe/Volgograd'},
      {label: '(UTC+03:30) Tehran', value: 'Asia/Tehran'},
      {label: '(UTC+04:00) Abu Dhabi', value: 'Asia/Muscat'},
      {label: '(UTC+04:00) Baku', value: 'Asia/Baku'},
      {label: '(UTC+04:00) Moscow', value: 'Europe/Moscow'},
      {label: '(UTC+04:00) Muscat', value: 'Asia/Muscat'},
      {label: '(UTC+04:00) St. Petersburg', value: 'Europe/Moscow'},
      {label: '(UTC+04:00) Tbilisi', value: 'Asia/Tbilisi'},
      {label: '(UTC+04:00) Yerevan', value: 'Asia/Yerevan'},
      {label: '(UTC+04:30) Kabul', value: 'Asia/Kabul'},
      {label: '(UTC+05:00) Islamabad', value: 'Asia/Karachi'},
      {label: '(UTC+05:00) Karachi', value: 'Asia/Karachi'},
      {label: '(UTC+05:00) Tashkent', value: 'Asia/Tashkent'},
      {label: '(UTC+05:30) Chennai', value: 'Asia/Calcutta'},
      {label: '(UTC+05:30) Kolkata', value: 'Asia/Kolkata'},
      {label: '(UTC+05:30) Mumbai', value: 'Asia/Calcutta'},
      {label: '(UTC+05:30) New Delhi', value: 'Asia/Calcutta'},
      {label: '(UTC+05:30) Sri Jayawardenepura', value: 'Asia/Calcutta'},
      {label: '(UTC+05:45) Kathmandu', value: 'Asia/Katmandu'},
      {label: '(UTC+06:00) Almaty', value: 'Asia/Almaty'},
      {label: '(UTC+06:00) Astana', value: 'Asia/Dhaka'},
      {label: '(UTC+06:00) Dhaka', value: 'Asia/Dhaka'},
      {label: '(UTC+06:00) Ekaterinburg', value: 'Asia/Yekaterinburg'},
      {label: '(UTC+06:30) Rangoon', value: 'Asia/Rangoon'},
      {label: '(UTC+07:00) Bangkok', value: 'Asia/Bangkok'},
      {label: '(UTC+07:00) Hanoi', value: 'Asia/Bangkok'},
      {label: '(UTC+07:00) Jakarta', value: 'Asia/Jakarta'},
      {label: '(UTC+07:00) Novosibirsk', value: 'Asia/Novosibirsk'},
      {label: '(UTC+08:00) Beijing', value: 'Asia/Hong_Kong'},
      {label: '(UTC+08:00) Chongqing', value: 'Asia/Chongqing'},
      {label: '(UTC+08:00) Hong Kong', value: 'Asia/Hong_Kong'},
      {label: '(UTC+08:00) Krasnoyarsk', value: 'Asia/Krasnoyarsk'},
      {label: '(UTC+08:00) Kuala Lumpur', value: 'Asia/Kuala_Lumpur'},
      {label: '(UTC+08:00) Perth', value: 'Australia/Perth'},
      {label: '(UTC+08:00) Singapore', value: 'Asia/Singapore'},
      {label: '(UTC+08:00) Taipei', value: 'Asia/Taipei'},
      {label: '(UTC+08:00) Ulaan Bataar', value: 'Asia/Ulan_Bator'},
      {label: '(UTC+08:00) Urumqi', value: 'Asia/Urumqi'},
      {label: '(UTC+09:00) Irkutsk', value: 'Asia/Irkutsk'},
      {label: '(UTC+09:00) Osaka', value: 'Asia/Tokyo'},
      {label: '(UTC+09:00) Sapporo', value: 'Asia/Tokyo'},
      {label: '(UTC+09:00) Seoul', value: 'Asia/Seoul'},
      {label: '(UTC+09:00) Tokyo', value: 'Asia/Tokyo'},
      {label: '(UTC+09:30) Adelaide', value: 'Australia/Adelaide'},
      {label: '(UTC+09:30) Darwin', value: 'Australia/Darwin'},
      {label: '(UTC+10:00) Brisbane', value: 'Australia/Brisbane'},
      {label: '(UTC+10:00) Canberra', value: 'Australia/Canberra'},
      {label: '(UTC+10:00) Guam', value: 'Pacific/Guam'},
      {label: '(UTC+10:00) Hobart', value: 'Australia/Hobart'},
      {label: '(UTC+10:00) Melbourne', value: 'Australia/Melbourne'},
      {label: '(UTC+10:00) Port Moresby', value: 'Pacific/Port_Moresby'},
      {label: '(UTC+10:00) Sydney', value: 'Australia/Sydney'},
      {label: '(UTC+10:00) Yakutsk', value: 'Asia/Yakutsk'},
      {label: '(UTC+11:00) Vladivostok', value: 'Asia/Vladivostok'},
      {label: '(UTC+12:00) Auckland', value: 'Pacific/Auckland'},
      {label: '(UTC+12:00) Fiji', value: 'Pacific/Fiji'},
      {label: '(UTC+12:00) International Date Line West', value: 'Pacific/Kwajalein'},
      {label: '(UTC+12:00) Kamchatka', value: 'Asia/Kamchatka'},
      {label: '(UTC+12:00) Magadan', value: 'Asia/Magadan'},
      {label: '(UTC+12:00) Marshall Is.', value: 'Pacific/Fiji'},
      {label: '(UTC+12:00) New Caledonia', value: 'Asia/Magadan'},
      {label: '(UTC+12:00) Solomon Is.', value: 'Asia/Magadan'},
      {label: '(UTC+12:00) Wellington', value: 'Pacific/Auckland'},
      {label: '(UTC+13:00) Nuku\'alofa', value: 'Pacific/Tongatapu'}
    ],
    hours: [
      {label: '01:00', value: '01:00'},
      // {label: '01:15', value: '01:15'},
      // {label: '01:30', value: '01:30'},
      // {label: '01:45', value: '01:45'},

      {label: '02:00', value: '02:00'},
      // {label: '02:15', value: '02:15'},
      // {label: '02:30', value: '02:30'},
      // {label: '02:45', value: '02:45'},

      {label: '03:00', value: '03:00'},
      // {label: '03:15', value: '03:15'},
      // {label: '03:30', value: '03:30'},
      // {label: '03:45', value: '03:45'},

      {label: '04:00', value: '04:00'},
      // {label: '04:15', value: '04:15'},
      // {label: '04:30', value: '04:30'},
      // {label: '04:45', value: '04:45'},

      {label: '05:00', value: '05:00'},
      // {label: '05:15', value: '05:15'},
      // {label: '05:30', value: '05:30'},
      // {label: '05:45', value: '05:45'},

      {label: '06:00', value: '06:00'},
      // {label: '06:15', value: '06:15'},
      // {label: '06:30', value: '06:30'},
      // {label: '06:45', value: '06:45'},

      {label: '07:00', value: '07:00'},
      // {label: '07:15', value: '07:15'},
      // {label: '07:30', value: '07:30'},
      // {label: '07:45', value: '07:45'},

      {label: '08:00', value: '08:00'},
      // {label: '08:15', value: '08:15'},
      // {label: '08:30', value: '08:30'},
      // {label: '08:45', value: '08:45'},

      {label: '09:00', value: '09:00'},
      // {label: '09:15', value: '09:15'},
      // {label: '09:30', value: '09:30'},
      // {label: '09:45', value: '09:45'},

      {label: '10:00', value: '10:00'},
      // {label: '10:15', value: '10:15'},
      // {label: '10:30', value: '10:30'},
      // {label: '10:45', value: '10:45'},

      {label: '11:00', value: '11:00'},
      // {label: '11:15', value: '11:15'},
      // {label: '11:30', value: '11:30'},
      // {label: '11:45', value: '11:45'},

      {label: '12:00', value: '12:00'},
      // {label: '12:15', value: '12:15'},
      // {label: '12:30', value: '12:30'},
      // {label: '12:45', value: '12:45'},
    ]
};
