export const CREATE_FOLDER_FAILED = 'CREATE_FOLDER_FAILED';
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
export const CREATE_TEXT_EMAIL_FAIL = 'CREATE_TEXT_EMAIL_FAIL';
export const UPDATE_EMAIL_PROPERTIES_FAIL = 'UPDATE_EMAIL_PROPERTIES_FAIL';
export const CREATE_HTML_EMAIL_FAIL = 'CREATE_HTML_EMAIL_FAIL';
export const GENERIC_ACTION_FAILED = 'GENERIC_ACTION_FAILED';
export const GENERIC_ACTION_SUCCESS = 'GENERIC_ACTION_SUCCESS';
export const CREATION_NOTIFICATION = 'CREATION_NOTIFICATION';

//Keep for other errors that will be handled
//export const GET_TEMPLATES_FOLDERS_FAIL = 'GET_TEMPLATES_FOLDERS_FAIL';
//
//export const GET_TEMPLATE_FOLDER_CONTENT_FAIL = 'GET_TEMPLATE_FOLDER_CONTENT_FAIL';
//
//export const MOVE_TEMPLATE_FOLDER_FAIL = 'MOVE_TEMPLATE_FOLDER_FAIL';
//
//export const RENAME_TEMPLATE_FOLDER_FAILED = 'RENAME_TEMPLATE_FOLDER_FAILED';
//
//export const DELETE_FOLDERS_AND_TEMPLATES_FAILED = 'DELETE_FOLDERS_AND_TEMPLATES_FAILED';
