export const GET_TEMPLATES_FOLDERS_START = 'GET_TEMPLATES_FOLDERS_START';
export const GET_TEMPLATES_FOLDERS_SUCCESS = 'GET_TEMPLATES_FOLDERS_SUCCESS';
export const GET_TEMPLATES_FOLDERS_FAIL = 'GET_TEMPLATES_FOLDERS_FAIL';

export const GET_TEMPLATE_FOLDER_CONTENT_START = 'GET_TEMPLATE_FOLDER_CONTENT_START';
export const GET_TEMPLATE_FOLDER_CONTENT_SUCCESS = 'GET_TEMPLATE_FOLDER_CONTENT_SUCCESS';
export const GET_TEMPLATE_FOLDER_CONTENT_FAIL = 'GET_TEMPLATE_FOLDER_CONTENT_FAIL';

export const COLLAPSE_ALL = 'COLLAPSE_ALL';
export const COLLAPSE_FOLDER = 'COLLAPSE_FOLDER';

export const CREATE_TEMPLATE_FOLDER_START = 'CREATE_TEMPLATE_FOLDER_START';
export const CREATE_TEMPLATE_FOLDER_SUCCESS = 'CREATE_TEMPLATE_FOLDER_SUCCESS';
export const CREATE_TEMPLATE_FOLDER_FAIL = 'CREATE_TEMPLATE_FOLDER_FAIL';

export const UPDATE_TEMPLATES_SORT_METHOD = 'UPDATE_TEMPLATES_SORT_METHOD';

export const GET_TEMPLATES_SUCCESS = 'GET_TEMPLATES_SUCCESS';
export const SELECT_ALL_TEMPLATES_ELEMENTS = 'SELECT_ALL_TEMPLATES_ELEMENTS';
export const SELECT_ELEMENT = 'SELECT_ELEMENT';
export const SELECT_TREE_ELEMENT = 'SELECT_TREE_ELEMENT';
export const SELECT_LIST_ELEMENT = 'SELECT_LIST_ELEMENT';
export const RESET_TEMPLATE_SELECTIONS = 'RESET_TEMPLATE_SELECTIONS';
export const RESET_MOVE_TO = 'RESET_MOVE_TO';

export const SET_MOVE_FOLDER_ID_TEMPLATES = 'SET_MOVE_FOLDER_ID_TEMPLATES';
export const SHOW_MOVE_MODAL_TEMPLATES = 'SHOW_MOVE_MODAL_TEMPLATES';
export const MOVE_TEMPLATE_FOLDER_START = 'MOVE_TEMPLATE_FOLDER_START';
export const MOVE_TEMPLATE_FOLDER_SUCCESS = 'MOVE_TEMPLATE_FOLDER_SUCCESS';
export const MOVE_TEMPLATE_FOLDER_FAIL = 'MOVE_TEMPLATE_FOLDER_FAIL';

export const RENAME_TEMPLATE_FOLDER_START = 'RENAME_TEMPLATE_FOLDER_START';
export const RENAME_TEMPLATE_FOLDER_SUCCESS = 'RENAME_TEMPLATE_FOLDER_SUCCESS';
export const RENAME_TEMPLATE_FOLDER_FAILED = 'RENAME_TEMPLATE_FOLDER_FAILED';
export const TOGGLE_RENAME_INPUT = 'TOGGLE_RENAME_INPUT';
export const SET_TEMPLATE_FOLDER_NAME = 'SET_TEMPLATE_FOLDER_NAME ';
export const VALIDATE_FOLDER_NAME = 'VALIDATE_FOLDER_NAME';
export const RESET_NEW_TEMPLATE_FOLDER = 'RESET_NEW_TEMPLATE_FOLDER';

export const SHOW_DELETE_MODAL_TEMPLATES = 'SHOW_DELETE_MODAL_TEMPLATES';
export const GET_SUBFOLDERS_NUMBER = 'GET_SUBFOLDERS_NUMBER';
export const GET_SELECTED_TEMPLATE_FOLDERS_DELETION = 'GET_SELECTED_TEMPLATE_FOLDERS_DELETION';
export const GET_TEMPLATE_SINGLE_DELETION_SELECTION = 'GET_TEMPLATE_SINGLE_DELETION_SELECTION';
export const RESET_TEMPLATE_DELETION_SELECTIONS = 'RESET_TEMPLATE_DELETION_SELECTIONS';
export const DELETE_FOLDERS_AND_TEMPLATES_SUCCESS = 'DELETE_FOLDERS_AND_TEMPLATES_SUCCESS';
export const DELETE_FOLDERS_AND_TEMPLATES_FAILED = 'DELETE_FOLDERS_AND_TEMPLATES_FAILED';

export const SET_TEMPLATE_SEARCH_TERM = 'SET_TEMPLATE_SEARCH_TERM';
export const SEARCH_TEMPLATES_START = 'SEARCH_TEMPLATES_START';
export const SEARCH_TEMPLATES_SUCCESS = 'SEARCH_TEMPLATES_SUCCESS';
export const SEARCH_TEMPLATES_FAIL = 'SEARCH_TEMPLATES_FAIL';
export const RESET_SEARCH_TEMPLATES = 'RESET_SEARCH_TEMPLATES';

export const APPLY_TEMPLATES_FILTERS_START = 'APPLY_TEMPLATES_FILTERS_START';
export const APPLY_TEMPLATES_FILTERS_SUCCESS = 'APPLY_TEMPLATES_FILTERS_SUCCESS';
export const APPLY_TEMPLATES_FILTERS_FAIL = 'APPLY_TEMPLATES_FILTERS_FAIL';
export const RESET_APPLY_FILTERS_TEMPLATES = 'RESET_APPLY_FILTERS_TEMPLATES';

export const GET_EMAILS_WITH_TEMPLATE_ID_START = 'GET_EMAILS_WITH_TEMPLATE_ID_START';
export const GET_EMAILS_WITH_TEMPLATE_ID_SUCCESS = 'GET_EMAILS_WITH_TEMPLATE_ID_SUCCESS';
export const GET_EMAILS_WITH_TEMPLATE_ID_FAIL = 'GET_EMAILS_WITH_TEMPLATE_ID_FAIL';

export const SEARCH_EMAILS_TEMPLATES_START = 'SEARCH_EMAILS_TEMPLATES_START';
export const SEARCH_EMAILS_TEMPLATES_SUCCESS = 'SEARCH_EMAILS_TEMPLATES_SUCCESS';
export const SEARCH_EMAILS_TEMPLATES_FAIL = 'SEARCH_EMAILS_TEMPLATES_FAIL';

export const GET_FULL_TEMPLATES_FOLDERS_START = 'GET_FULL_TEMPLATES_FOLDERS_START';
export const GET_FULL_TEMPLATES_FOLDERS_SUCCESS = 'GET_FULL_TEMPLATES_FOLDERS_SUCCESS';
export const GET_FULL_TEMPLATES_FOLDERS_FAIL = 'GET_TEMPLATES_FOLDERS_FAIL';

export const SET_CHANGE_TEMPLATE = 'SET_CHANGE_TEMPLATE';

export const PUBLISH_TEMPLATE_START = 'PUBLISH_TEMPLATE_START';
export const PUBLISH_TEMPLATE_SUCCESS = 'PUBLISH_TEMPLATE_SUCCESS';
export const PUBLISH_TEMPLATE_FAIL = 'PUBLISH_TEMPLATE_FAIL';

export const UNPUBLISH_TEMPLATE_START = 'UNPUBLISH_TEMPLATE_START';
export const UNPUBLISH_TEMPLATE_SUCCESS = 'UNPUBLISH_TEMPLATE_SUCCESS';
export const UNPUBLISH_TEMPLATE_FAIL = 'UNPUBLISH_TEMPLATE_FAIL';
